old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 6
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: false # default false
#        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
#            url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
#            url: '%env(RABBITMQ_URL)%'
    producers:
      confirm_sign_up:
        connection:       default
        exchange_options: {name: 'app.confirm-sign-up', type: direct}
      reset_password:
        connection:       default
        exchange_options: {name: 'app.reset-password', type: direct}
    consumers:
      confirm_sign_up:
        connection:       default
        exchange_options: {name: 'app.confirm-sign-up', type: direct}
        queue_options:    {name: 'app.confirm-sign-up'}
        callback:         App\Consumer\SignUpConfirmationConsumer
      reset_password:
        connection:       default
        exchange_options: {name: 'app.reset-password', type: direct}
        queue_options:    {name: 'app.reset-password'}
        callback:         App\Consumer\ResetPasswordConsumer
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer